name: My First Robot Helper

on:
  push:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: 25ds1000107@ds.study.iitm.ac.in
        run: echo "Hello! I am your robot helper!"
      
      - name: Tell me the date
        run: echo "Today is $(date)"
      
      - name: Do a fun calculation
        run: echo "2 + 2 equals 4"
